Feature/set app views
Felipe-Perez-Ferraro/blog_app pull request #8
Opened 2023-11-08 16:58 UTC by Felipe-Perez-Ferraro

- Added functionalities to index and show methods in posts_controller
- Added functionalities to index and show methods in users_controller
- Created the view of posts#index
- Created the view of posts#show
- Created the view of users#index
- Created the view of users#show

2023-11-08 18:02 UTC, Gambit142 requested changes
Hi @Felipe-Perez-Ferraro 👋, 

Good job so far!

## Highlights
- Setup linters correctly ✔️ 
- Created view files for the `Users` controller ✔️ 
- Created view files for the `Posts` controller ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-11-08 18:02 UTC, Gambit142 commented on app/views/users/index.html.erb
> +<% end %>
- [ ] One of the requirements for this project is to ensure that different views are identical to that of the wireframe provided for the view. On the `Users#Index` page, the user's name and other details should be placed on the same row as the user's picture not under the picture. Kindly implement this change 👍 😎 

### Your `Users#Index` Page

![image](https://github.com/Felipe-Perez-Ferraro/blog_app/assets/77106962/9d9750b4-a90a-40c5-9acd-4debe4d48625)

### Wireframe Provided

![image](https://github.com/Felipe-Perez-Ferraro/blog_app/assets/77106962/6b1946eb-0a7e-44e1-9033-cf3096e71901)

2023-11-08 18:02 UTC, Gambit142 commented on app/views/users/index.html.erb
> +<% end %>
- [OPTIONAL] It would have been nice to use a partial to render this page as the features of this page are almost the same as most of the views for this application. You can read more on rails [partials](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials:~:text=otherwise%20generic%20layout.-,3.4%20Using%20Partials,-Partial%20templates%20%2D%20usually). 😎 👍

2023-11-08 18:02 UTC, Gambit142 commented on app/models/user.rb
> +    posts.order(created_at: :asc).limit(3)
- [ ] The `order_user_posts` method should return the three most recent posts for a user. This means that the posts will not return as first in first to be displayed but based on last to be created first to be displayed. Kindly undo this change you made here. 👍 💻

2023-11-08 18:02 UTC, Gambit142 commented on app/views/users/show.html.erb
> +
- [ ] One of the requirements for this project is to ensure that different views are identical to that of the wireframe provided for the view. On the `Users#Show` page, the user's name and other details should be placed on the same row as the user's picture not under the picture. Kindly implement this change. This is a good reason to use partials since this feature appears on most of the pages in this application. 👍 😎 

### Your `Users#Show` Page

![image](https://github.com/Felipe-Perez-Ferraro/blog_app/assets/77106962/9277115a-593d-4d07-af4d-2ac6d568d25d)

### Wireframe Provided

![image](https://github.com/Felipe-Perez-Ferraro/blog_app/assets/77106962/58ab9e4a-3532-4d3d-bab8-33de8c663c93)

2023-11-08 18:02 UTC, Gambit142 commented on app/views/posts/index.html.erb
> +  <% end %>
- [ ] One of the requirements for this project is to ensure that different views are identical to that of the wireframe provided for the view. On the `Posts#Index` page, the user's name and other details should be placed on the same row as the user's picture not under the picture. Kindly implement this change. This is a good reason to use partials since this feature appears on most of the pages in this application. 👍 😎 

### Your `Posts#Index` Page

![image](https://github.com/Felipe-Perez-Ferraro/blog_app/assets/77106962/02a892aa-c37c-4f34-8f61-6c46afd1c9a6)

### Wireframe Provided

![image](https://github.com/Felipe-Perez-Ferraro/blog_app/assets/77106962/e3664f14-c42d-4812-b612-36be664ed24d)

2023-11-08 18:02 UTC, Gambit142 commented on app/views/posts/index.html.erb
> +  <% end %>
- [ ] One of the features on the `Posts#Index` page is to have the pagination button. Your `Posts#Index` page doesn't have that button currently. Kindly create one 💻 🖱️

2023-11-08 18:02 UTC, Gambit142 commented on app/views/posts/show.html.erb
> +
- [ ] One of the requirements for this project is to ensure that different views are identical to that of the wireframe provided for the view. On the `Posts#Show` page, the details about **_the comments and likes for the post_** should be on the same row with the **_user's name and the post's title_** but at the far end. 👍 🖱️ 

### Your `Posts#Show` Page

![image](https://github.com/Felipe-Perez-Ferraro/blog_app/assets/77106962/cb8a2059-fc4a-4df5-a064-d0cd951f2a66)

### Wireframe Provided

![image](https://github.com/Felipe-Perez-Ferraro/blog_app/assets/77106962/017b23f7-01cf-40f5-8601-23c35a6712ab)

2023-11-09 23:59 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 ✔️ 

## Hi @Felipe-Perez-Ferraro 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/2RGhmKXcl0ViM/giphy.gif"/>

## Highlights 🎯 
- Setup linters correctly ✔️
- Created view files for the Users controller ✔️
- Created view files for the Posts controller ✔️


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-10 16:34 UTC, merged